### ISSUE TITLE
yeacs.nim potential aliasing issue?

### ISSUE THREAD

**Issue by guzba** [beef331/nimtrest#1]
Having recently learned more about the strict aliasing rule, I noticed when looking at this for the ECS stuff that I do fear the rule may be being broken here: https://github.com/beef331/nimtrest/blob/master/yeacs.nim#L96 (any time you deref that pointer for anything other than a byte/char/uint8 / whenever val isn't one of those)

This is the frustrating part of the strict aliasing rule, eg https://news.ycombinator.com/item?id=11289995

I could totally be mistaken though? Would not mind learning more since it seems like a very crippling rule.

**Comment by beef331** [comment]
Yea I realized it may be an issue. I'm uncertain if it relies on UB or not in this case. Luckily for me this isn't a serious implementation of ECS so if it doesnt work it's no big deal. It's very much a for fun macro-less implementation of ECS with no intention of being used as is.

**Comment by guzba** [comment]
Gotcha, no worries then, imo it should be fine but im not a compiler haha.

**Comment by beef331** [comment]
I do wonder if the following is sufficient to not break the rule given that there is no pointer made for the element I do not see that there'd any aliasing.... though could be wrong.
```nim
let colStart = cast[int](arch.data[0].addr)
cast[ptr val](colStart + ind * arch.stride + arch.componentOffset[indArray[i]] - sizeof(pointer))
```

**Comment by guzba** [comment]
The difficulty here for me is "what is wrong" vs "what doesn't work". I think it's very difficult to be sure something is fully correct if you do any casting of any kind at least with my current understanding.

However, in this specific case, there is data: seq[byte] itself, which contains a pointer, so the cast-ed arch.data[0].addr is an alias of the seq's pointer of type byte and this alias is used for a different type than the effective type at allocation of that memory.

Perhaps since you don't ever use it for any other type / size, it'd be fine? And I'd have to check, but you don't ever access data via data[] indices so that'd avoid that alias being a concern maybe?

I think, concretely, if you can't reproduce an issue, theorizing about this could result in chasing your tail and never knowing if what you did made a difference unfortunately.
